### PR TITLE
✨ Implement hillshading configurable highlight&shade colors

### PR DESCRIPTION
**Pull request by V-Roger**
Addresses https://github.com/openlayers/ol-mapbox-style/issues/725

### CODE REVIEW

**Comment by utagawal** [comment]
Caution : in Mapbox there are 3 colors set in the layer specification : highlight, shadow and accent => https://docs.mapbox.com/android/maps/api/10.0.0-rc.1/-mapbox%20-maps%20-android/com.mapbox.maps.extension.style.layers.generated/-hillshade-layer/

**Comment by V-Roger** [comment]
> Caution : in Mapbox there are 3 colors set in the layer specification : highlight, shadow and accent => https://docs.mapbox.com/android/maps/api/10.0.0-rc.1/-mapbox%20-maps%20-android/com.mapbox.maps.extension.style.layers.generated/-hillshade-layer/

Woops I missed the accent. I'll look into it tonight, I'm not used to mapbox ;)

**Comment by V-Roger** [comment]
image

**Comment by utagawal** [comment]
Thanks for the implementation. A new funcvtional extension has been registered if you'de like to continue to help 👉 #755

**Comment by V-Roger** [comment]
Sure thing @ahocevar !
The underlying hillshader seems to output OK, but we do have some opacity issues.
Looking into it later today :)

**Comment by V-Roger** [comment]
Screenshot from 2022-12-07 11-30-38

Austria does look better once the opacity is dropped to 0.25

**Comment by ahocevar** [comment]
It is still much darker than the reference. I think what's needed is a dynamic opacity. Less opacity when flat, more opacity when steep. This would also bring the result closer to the slope accentuation in the reference.

**Comment by ahocevar** [comment]
@V-Roger Is this ready for a final review? If so, please mark it "Ready for review".

**Comment by utagawal** [comment]
Many thanks both of you !

**Comment by V-Roger** [comment]
My pleasure, it's also my first ever real OpenSource contribution so I'm thrilled :D

**Pull request merged**
