### PR TITLE
Fix package with proper .npmignore

### PR DESCRIPTION
**Pull request by ahocevar**
The package broke with #189. This pull request fixes it.

### CODE REVIEW

**Comment by fredj** [comment]
This is strange; according to the [npmignore documentation](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package), the `.git` directory is automatically included

**Comment by ahocevar** [comment]
Obviously not. See the failing OpenLayers builds in circleci.

**Comment by fredj** [comment]
Without this change, `.git` is correctly ignored when I run `npm pack`:
```bash
$ npm --version
6.4.1
$ npm pack
[...]
npm notice 
npm notice 📦  ol-mapbox-style@4.3.0
npm notice === Tarball Contents === 
npm notice 1.9kB   package.json                   
npm notice 8.7kB   CHANGELOG.md                   
npm notice 25.9kB  index.js                       
npm notice 1.3kB   LICENSE                        
npm notice 260B    olms.js                        
npm notice 1.5kB   PUBLISHING.md                  
npm notice 15.9kB  README.md                      
npm notice 26.7kB  stylefunction.js               
npm notice 4.1kB   util.js                        
npm notice 5.2kB   dist/common.css                
npm notice 7.0kB   dist/common.css.map            
npm notice 714.5kB dist/common.js                 
npm notice 2.9MB   dist/common.js.map             
npm notice 23.4kB  dist/data/geojson-inline.json  
npm notice 1.9kB   dist/data/geojson.json         
npm notice 173B    dist/data/sprites.json         
npm notice 2.1kB   dist/data/sprites.png          
npm notice 176B    dist/data/sprites@2x.json      
npm notice 4.5kB   dist/data/sprites@2x.png       
npm notice 565.9kB dist/data/states.geojson       
npm notice 1.8kB   dist/data/states.json          
npm notice 472B    dist/data/tilejson.json        
npm notice 1.1kB   dist/data/wms.json             
npm notice 703B    dist/geojson-inline.html       
npm notice 218B    dist/geojson-inline.js         
npm notice 444B    dist/geojson-inline.js.map     
npm notice 696B    dist/geojson.html              
npm notice 204B    dist/geojson.js                
npm notice 423B    dist/geojson.js.map            
npm notice 1.5kB   dist/index.html                
npm notice 695B    dist/mapbox.html               
npm notice 487B    dist/mapbox.js                 
npm notice 959B    dist/mapbox.js.map             
npm notice 381.2kB dist/olms.js                   
npm notice 986.5kB dist/olms.js.map               
npm notice 701B    dist/openmaptiles.html         
npm notice 502B    dist/openmaptiles.js           
npm notice 980B    dist/openmaptiles.js.map       
npm notice 702B    dist/stylefunction.html        
npm notice 551B    dist/stylefunction.js          
npm notice 2.0kB   dist/stylefunction.js.map      
npm notice 698B    dist/swisstopo.html            
npm notice 282B    dist/swisstopo.js              
npm notice 499B    dist/swisstopo.js.map          
npm notice 708B    dist/tilejson-vectortile.html  
npm notice 242B    dist/tilejson-vectortile.js    
npm notice 473B    dist/tilejson-vectortile.js.map
npm notice 697B    dist/tilejson.html             
npm notice 206B    dist/tilejson.js               
npm notice 426B    dist/tilejson.js.map           
npm notice 692B    dist/wms.html                  
npm notice 196B    dist/wms.js                    
npm notice 407B    dist/wms.js.map                
npm notice === Tarball Details === 
npm notice name:          ol-mapbox-style                         
npm notice version:       4.3.0                                   
npm notice filename:      ol-mapbox-style-4.3.0.tgz               
npm notice package size:  1.3 MB                                  
npm notice unpacked size: 5.7 MB                                  
npm notice shasum:        03937a65068953e813019cc114e6c919f9185786
npm notice integrity:     sha512-yOKg1TX6M+VMX[...]6nLYYXBlrVfLQ==
npm notice total files:   53                                      
npm notice 
ol-mapbox-style-4.3.0.tgz
```

**Comment by ahocevar** [comment]
Anyway, `npm publish` for v4.3.0 created a package with a `.git/` directory: https://unpkg.com/ol-mapbox-style@4.3.0/.

**Comment by ahocevar** [comment]
Actually this is a weird npm bug. See https://npm.community/t/npmignore-git-directory-included-when-a-remote-has-a-branch-named-changelog/6798.

**Comment by fredj** [comment]
good find !

**Pull request merged**
